import { defineStyle, extendTheme } from '@chakra-ui/react';

// TODO EA theme
export const theme = extendTheme({
  colors: {
    'foreground-bg': '#fbfbfb',
    'background-bg': '#f2f2f2',
    // generated by https://hihayk.github.io/scale/#3/6/63/96/8/71/20/14/007878/0/121/120/white
    primary: {
      '900': '#003029',
      '800': '#004942',
      '700': '#00615D',
      '600': '#007878',
      '500': '#298F7B',
      '400': '#52A684',
      '300': '#7ABC93',
      '200': '#A3D1AB',
      '100': '#CCE6CC',
      '50': '#F5FAF5',
    },
    // generated by https://hihayk.github.io/scale/#5/4/78/96/8/0/20/100/3182CE/49/130/206/white
    blue: {
      '900': '#002638',
      '800': '#003D60',
      '700': '#015187',
      '600': '#0C62A3',
      '500': '#1C72BB',
      '400': '#3182CE',
      '300': '#60A0DD',
      '200': '#90BEEA',
      '100': '#C2DCF5',
      '50': '#F6FAFE',
    },
  },

  components: {
    Heading: {
      sizes: {
        'page-heading': {
          fontSize: '2xl',
          mb: 1,
        },
      },
    },
    Popover: {
      baseStyle: {
        content: {
          boxShadow: 'md',
        },
        header: {
          bg: 'gray.50',
        },
      },
    },
    Radio: {
      baseStyle: {
        container: {
          w: 'fit-content',
        },
      },
    },
    Table: {
      baseStyle: {
        table: {
          borderCollapse: 'separate',
          borderSpacing: 0,
        },
        thead: {
          tr: {
            bg: 'gray.100',
            th: {
              borderColor: 'gray.200',
              borderTopWidth: '1px',
              borderTopStyle: 'solid',
            },
            '& th:first-of-type': {
              borderTopLeftRadius: 'md',
              borderBottomLeftRadius: 'md',
              borderLeftWidth: '1px',
              borderLeftStyle: 'solid',
            },
            '& th:last-child': {
              borderTopRightRadius: 'md',
              borderBottomRightRadius: 'md',
              borderRightWidth: '1px',
              borderRightStyle: 'solid',
            },
          },
        },
        tbody: {
          tr: {
            td: {
              borderTop: '1px solid',
              borderBottom: '1x solid',
              borderColor: 'transparent',
            },
            '& td:first-of-type': {
              borderTopLeftRadius: 'md',
              borderBottomLeftRadius: 'md',
              borderLeftWidth: '1px',
              borderLeftStyle: 'solid',
            },
            '& td:last-child': {
              borderTopRightRadius: 'md',
              borderBottomRightRadius: 'md',
              borderRightWidth: '1px',
              borderRightStyle: 'solid',
            },
            '&:hover td, &:has(button[aria-expanded="true"]) td, &:has(button[data-loading]) td': {
              bg: 'gray.100',
              borderColor: 'gray.200',
            },
            '& .row-hover': {
              visibility: 'hidden',
            },
            '&:hover .row-hover, &:has(button[aria-expanded="true"]) .row-hover, &:has(button[data-loading]) .row-hover':
              {
                visibility: 'visible',
              },
          },
        },
      },
      sizes: {
        sm: {
          thead: {
            tr: {
              th: {
                px: 4,
                py: 2,
              },
            },
          },
        },
      },
      defaultProps: {
        size: 'sm',
      },
    },
    Button: {
      sizes: {
        table: {
          h: 6,
          minW: 6,
          fontSize: 'md',
          margin: 'calc(-2px - 0.25rem)',
        },
        'table-row': {
          h: '2rem',
          fontSize: 'md',
          px: '0.5em',
          borderRadius: 0,
        },
        'action-bar': {
          fontSize: 'md',
          px: '0.5em',
          h: 8,
        },
      },
      variants: {
        'outline-highlight': defineStyle((props) => {
          const { colorScheme: c } = props;
          return {
            border: '1px solid',
            borderColor: c === 'gray' ? 'gray.200' : 'currentColor',
            '.chakra-button__group[data-attached][data-orientation=horizontal] > &:not(:last-of-type)':
              { marginEnd: '-1px' },
            '.chakra-button__group[data-attached][data-orientation=vertical] > &:not(:last-of-type)':
              { marginBottom: '-1px' },
            ...(c === 'gray'
              ? {
                  color: `gray.900`,
                  bg: `gray.50`,
                  _hover: {
                    bg: `gray.100`,
                  },
                  _active: { bg: `gray.200` },
                }
              : {
                  color: `${c}.800`,
                  bg: `${c}.50`,
                  _hover: {
                    bg: `${c}.100`,
                  },
                  _active: {
                    bg: `${c}.200`,
                  },
                }),
          };
        }),
        'ghost-dark': defineStyle((props) => {
          const { colorScheme: c } = props;

          if (c === 'gray') {
            return {
              color: 'gray.600',
              _hover: {
                bg: `gray.200`,
              },
              _active: { bg: `gray.300` },
            };
          }

          return {
            color: `${c}.600`,
            bg: 'transparent',
            _hover: {
              bg: `${c}.100`,
            },
            _active: {
              bg: `${c}.200`,
            },
          };
        }),
      },
    },
    FormLabel: {
      baseStyle: {
        mt: 4,
        mb: 1,
        fontWeight: 'semibold',
      },
      variants: {
        view: {
          color: 'gray.500',
          mb: 1,
          mt: 0,
          fontWeight: 'normal',
        },
      },
    },
    FormError: {
      baseStyle: {
        text: {
          marginTop: 1,
          whiteSpace: 'pre-line',
        },
      },
    },
    Tag: {
      baseStyle: {
        container: { fontFamily: 'mono', fontWeight: 'semibold' },
      },
    },
    Card: {
      variants: {
        elevated: {
          container: {
            borderWidth: '1px',
            borderColor: 'border',
            boxShadow: 'lg',
            _dark: {
              bg: 'gray.700',
            },
          },
        },
      },
    },
  },
  shadows: {
    xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    base: '0 1px 3px 0 rgba(0, 0, 0, 0.07), 0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -1px rgba(0, 0, 0, 0.05)',
    lg: '2px 4px 15px -3px rgba(0, 0, 0, 0.07), 0 4px 6px -2px rgba(0, 0, 0, 0.04)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.07), 0 10px 10px -5px rgba(0, 0, 0, 0.03)',
    '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.15)',
    outline: '0 0 0 3px rgba(66, 153, 225, 0.4)',
    inner: 'inset 0 2px 4px 0 rgba(0,0,0,0.05)',
    'inner-md': 'inset 0 2px 7px 0 rgba(0,0,0,0.07)',
    none: 'none',
    'dark-lg':
      'rgba(0, 0, 0, 0.1) 0px 0px 0px 1px, rgba(0, 0, 0, 0.2) 0px 5px 10px, rgba(0, 0, 0, 0.4) 0px 15px 40px',
  },
  fonts: {
    body: `'IBM Plex Sans', sans-serif`,
  },
  sizes: {
    'form-width': '28em',
  },
  styles: {
    global: {
      '*::placeholder': {
        fontStyle: 'italic',
      },
      '.chakra-collapse[style*="height: auto"] { overflow: initial !important }': {
        overflow: 'initial',
      },
    },
  },
});
export const globalTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    primary: {
      '900': '#FA0000',
      '800': '#FC0F00',
      '700': '#FD1F00',
      '600': '#FF2F00',
      '500': '#FF2929',
      '400': '#FF5273',
      '300': '#FF7AAF',
      '200': '#FFA3DC',
      '100': '#FFCCF8',
      '50': '#FFF5FF',
      // generated by https://hihayk.github.io/scale/#4/6/50/80/-51/67/20/14/FA0000/250/0/0/l-2
    },
  },
  styles: {
    ...theme.styles,
    global: {
      ...theme.styles.global,
      '#borderGlobal': { border: '3px solid red', borderRadius: '1em' },
    },
  },
};
