@multitenantUrl=https://localhost/odsv7-adminv3-multi-adminapi
@singletenantUrl=https://localhost/odsv7-adminv3-single-adminapi

@adminapi_url={{multitenantUrl}}
@adminapi_client=adminapi_client2
@adminapi_secret=adminapi_SECRET_2025_rftyguhijkotgyhuijok
@tenant=tenant2

### Register a new client
POST {{adminapi_url}}/connect/register
Content-Type: application/x-www-form-urlencoded
Tenant: {{tenant}}

ClientId={{adminapi_client}}&ClientSecret={{adminapi_secret}}&DisplayName=Admin+API+{{adminapi_client}}

### Get a token
# @name tokenRequest
POST {{adminapi_url}}/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: basic {{adminapi_client}}:{{adminapi_secret}}
Tenant: {{tenant}}

grant_type=client_credentials&scope=edfi_admin_api/full_access

###
@token={{tokenRequest.response.body.access_token}}


### Create a manage datastore (Minimal template)
# @name createDbDataStoreMinimal
POST {{adminapi_url}}/v3/dataStores/manage
Content-Type: application/json
Authorization: bearer {{token}}
Tenant: {{tenant}}

{
  "name": "My DB Datastores 3",
  "databaseTemplate": "Minimal"
}

### Create a datastore (Sample template)
# @name createDbDataStoreSample
POST {{adminapi_url}}/v3/dataStores/manage
Content-Type: application/json
Authorization: bearer {{token}}
Tenant: {{tenant}}

{
  "name": "My Sample DB Datastore",
  "databaseTemplate": "Sample"
}

### Get all manage datastores
GET {{adminapi_url}}/v3/dataStores/manage
Content-Type: application/json
Authorization: bearer {{token}}
Tenant: {{tenant}}

### Get all datastores
GET {{adminapi_url}}/v3/datastores
Content-Type: application/json
Authorization: bearer {{token}}
Tenant: {{tenant}}

### DELETE a manage datastore (Minimal)
DELETE {{createDbDataStoreMinimal.response.headers.location}}
Content-Type: application/json
Authorization: bearer {{token}}
Tenant: {{tenant}}

### DELETE a manage datastore (Sample)
DELETE {{createDbDataStoreSample.response.headers.location}}
Content-Type: application/json
Authorization: bearer {{token}}
Tenant: {{tenant}}
